export type Song = {
  id?: number; // Optional: will be auto-generated by IndexedDB
  title: string;
  artist: string;
  fileUrl: string;
  characteristics: string[];
  file?: File; // Optional: only present for user-uploaded songs
};

export type Playlist = {
    id: string | number; // Firestore uses string, Dexie uses number
    name: string;
    songIds: number[];
    isPublic: boolean; // To distinguish between public (Firestore) and private (Dexie)
};
